server:
  port: 8082

spring:
  application:
    name: Hotel-Service

  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_rating_app
    username: postgres
    password: saurav
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: configserver:http://localhost:8085

  mail:
    host: smtp.gmail.com
    port: 587
    username: saurav.kumar3279@gmail.com
    password: qcon ogzo vgbm atgy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: consumer-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka