server:
  port: 8081

spring:
  application:
    name: User-Service

  datasource:
    url: jdbc:mysql://localhost:3306/hotel_rating_app
    username: root
    password: saurav
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: configserver:http://localhost:8085

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      serviceBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      serviceRetry:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      serviceLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
